name: Deploy to GitHub Pages

on:  
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy-check:
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
    env: 
      CONFIGCAT_API_USER: ${{ secrets.CONFIGCAT_API_USER }}
      CONFIGCAT_API_PASS: ${{ secrets.CONFIGCAT_API_PASS }}
    outputs:
      build-deploy-enabled: ${{ steps.bd-flag.outputs.build_deploy_enabled }}
    steps:
      - name: Check build and deploy flag
        id: bd-flag
        uses: configcat/cli-actions/eval-flag@v1
        with:
          sdk-key: ${{ secrets.CONFIGCAT_SDK_KEY}}
          flag-keys: 
            build_deploy_enabled

  build:
    needs: build-deploy-check
    if: needs.build-deploy-check.outputs.build-deploy-enabled == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5
      - name: Install, build, and upload your site
        uses: withastro/action@v5

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4